language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cd asn1-cereal; cargo build --verbose; cargo test --verbose
  - cd ..
  - cd asn1-utils; cargo build --verbose; cargo test --verbose

after_success:
  - travis-cargo bench --only stable
  - travis-cargo coveralls --no-sudo
