[package]
name = "asn1-nom"
version = "0.1.0"
authors = ["Josh <keeperofdakeys@gmail.com>"]

[lib]
path = "src/lib.rs"
name = "run"

[dependencies]
# nom = "^1.2"
# Use our nom for the eol patch
nom = { path = "../../nom" }
